targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
      - skills/**
    builders:
      pubspec_generator:
        options:
          output: lib/constants/pubspec.g.dart
