name: package_1
description: A starting point for Dart libraries or applications.
version: 1.2.3
resolution: workspace
publish_to: none
homepage: https://example.com/package_1
repository: https://github.com/exaby73/dpk/tree/main/examples/monorepo/packages/package_1
issue_tracker: https://github.com/exaby73/dpk/issues
documentation: https://pub.dev/documentation/package_1/1.2.3/
topics:
  - dpk
funding:
  - https://github.com/sponsors/package_1

platforms:
  linux: null
  macos: null

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  luthor: # Configured via catalog
    git:
      url: https://github.com/exaby73/luthor.git
      path: packages/luthor
  meta: 1.15.0 # Configured via catalog

dev_dependencies:
  build_runner: 2.4.15 # Configured via catalog
  freezed: ^3.0.6
  lints: ^5.0.0
  test: ^1.24.0
