name: package_2
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
publish_to: none
repository: https://github.com/exaby73/dpk/tree/main/examples/monorepo/packages/package_2
documentation: https://pub.dev/documentation/package_2/1.0.0/
topics:
  - dpk

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  luthor:
    git:
      url: https://github.com/exaby73/luthor.git
      path: packages/luthor
  meta: 1.15.0

dev_dependencies:
  build_runner: 2.4.15
  freezed: ^3.0.6
  lints: ^5.0.0
  test: ^1.24.0
