name: package_2
description: A starting point for Dart libraries or applications.
version: 1.2.3
resolution: workspace
publish_to: none
homepage: https://example.com/package_2
repository: https://github.com/exaby73/dpk/tree/main/examples/monorepo/packages/package_2
issue_tracker: https://github.com/exaby73/dpk/issues
documentation: https://pub.dev/documentation/package_2/1.2.3/
topics:
  - dpk
funding:
  - https://github.com/sponsors/package_2

platforms:
  linux: null
  macos: null

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  luthor: # Configured via catalog
    git:
      url: https://github.com/exaby73/luthor.git
      path: packages/luthor
  meta: 1.19.0 # Configured via catalog

dev_dependencies:
  lints: ^6.1.0 # Configured via catalog
  test: ^1.32.0 # Configured via catalog
